[package]
name = "central"
version = "0.1.0"
authors = ["wess <wcope@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
